### ISSUE TITLE
Motortreiber (H-Brücke)

### ISSUE THREAD

**Issue by FluYVy** [FluYVy/Modular-Electronics-Toolkit#14]
TB6612FNG,C,8,EL was ordered. Other Chips may be used. [Digikey](https://www.digikey.at/en/products/detail/toshiba-semiconductor-and-storage/TB6612FNG-C-8-EL/1730070)

**Comment by ObiLanKenobiLukas** [comment]
This Module provides an H-Bridge combined with a little DC Motor.

**Comment by FluYVy** [comment]
Redundant. HTL Rankweil already has one.
